# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240207-100712-seething-force

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline: 
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200  # Increase epochs for better learning
    constrain_similarities: true
  - name: EntitySynonymMapper

  - name: FallbackClassifier
    threshold: 0.5  # Adjust threshold as needed
    ambiguity_threshold: 0.3  # Adjust ambiguity threshold as needed


policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 10  # Adjust max_history as needed
    epochs: 200  # Increase epochs for better learning
  - name: RulePolicy
 




# config.yml
# ...
server:
  cors: "*"
  # Other server configurations

